### ISSUE TITLE
Help Error on launching hive 

### ISSUE THREAD

**Issue by WilliamFoster** [bbc/hive-runner-android#87]
Hi, 

I cannot seem to understand what is happening there it happens after i add in the settings.yml the android workers. Everything else is running fine. Here are the logs you seem to need in order to help me after checking some questions that were already asked.

start_hive: process with pid 8541 started.
*** Starting Hive at 2017-02-13 17:16:23 +0100 ***
NOTE: Specification.all called from /var/lib/gems/2.3.0/gems/hive-runner-2.1.21/bin/start_hive:27:in `<top (required)>'
/var/lib/gems/2.3.0/gems/hive-runner-2.1.21/lib/hive/register.rb:36:in `require': cannot load such file -- hive/controller/android (LoadError)
	from /var/lib/gems/2.3.0/gems/hive-runner-2.1.21/lib/hive/register.rb:36:in `block in instantiate_controllers'
	from /var/lib/gems/2.3.0/gems/hive-runner-2.1.21/lib/hive/register.rb:34:in `each'
	from /var/lib/gems/2.3.0/gems/hive-runner-2.1.21/lib/hive/register.rb:34:in `instantiate_controllers'
	from /var/lib/gems/2.3.0/gems/hive-runner-2.1.21/bin/start_hive:122:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:219:in `load'
	from /var/lib/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:219:in `start_load'
	from /var/lib/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:298:in `start'
	from /var/lib/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/controller.rb:56:in `run'
	from /var/lib/gems/2.3.0/gems/daemons-1.2.4/lib/daemons.rb:148:in `block in run'
	from /var/lib/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `catch_exceptions'
	from /var/lib/gems/2.3.0/gems/daemons-1.2.4/lib/daemons.rb:147:in `run'
	from /var/lib/gems/2.3.0/gems/hive-runner-2.1.21/bin/hived:31:in `<top (required)>'
	from /usr/local/bin/hived:22:in `load'
	from /usr/local/bin/hived:22:in `<main>'

bundle list daemons 
/var/lib/gems/2.3.0/gems/daemons-1.2.4

**Comment by Asimk21** [comment]
@WilliamFoster : Have you added hive-runner-android gem in Gemfile?

If not, add `gem 'hive-runner-android' in Gemfile and do `bundle install` and try again.

**Comment by WilliamFoster** [comment]
@Asimk21 : that step has already been done and nothing has changed :(

**Comment by Asimk21** [comment]
`cannot load such file -- hive/controller/android (LoadError)` looks like it couldn't find 'hive-runner-android' gem. Can you please check the `hive-runner` and `hive-runner-android` version please? 
`bundle show hive-runner-android`

**Comment by WilliamFoster** [comment]
@Asimk21 :

bundle show hive-runner-android
/var/lib/gems/2.3.0/gems/hive-runner-android-1.2.14

bundle show hive-runner
/var/lib/gems/2.3.0/gems/hive-runner-2.1.2

there you go

**Comment by jrmhaig** [comment]
Can you please paste the top (controllers) section of your settings file.

**Comment by WilliamFoster** [comment]
@jrmhaig 
```yml
controllers:
    shell:
      # Number of shell workers to allocate
      workers: 5
      # Queue for each shell worker
      queues:
        - bash
      # Number of ports to allocate to each shell worker
      port_range_size: 50
      name_stub: SHELL_WORKER
    android:
      port_range_size: 10
      name_stub: ANDROID_WORKER
  ```
